---
output: github_document
---
<!-- README.md is generated from README.Rmd. Please edit that file -->
## Tutorial for simuation with `sCCIgen` interactive interface. 


In R (or R Studio), open the Rshiny interface by running: 

```R
library(sCCIgen)
run_interactive_sCCIgen()
````
It will show you three tasks to choose from: 

#### Task 1: I want to download a pre-simulated spatial transcriptomics dataset. 

`sCCIgen` provides three pre-simulated datasets. You can quickly check the data format and explore your analyses before spending efforts on learning the package and simulating data. These datasets are simulated based on normal breast snRNAseq, mouse brain SeqFISH+, and human ovarian cancer MERFISH. 

Here,  select one example data and it will be downloaded to your working directory. 

#### Task 2: I want to generate a parameter file using command line prompts.

If you select Task 2, `sCCIgen` will first walk you through a number of parameter selection questions to help you generate a parameter file. The first question is to select the data for simulation. Playing with the decoy data may help you to get familiar with the simulator, while spending little  time on waiting for the simulation results. You can also use our built-in real data by selection (4-6) or your input data by selecting "user input".   


#### Task 3: I have a parameter file and want to run a simulation.
Finally, you have the parameter file and can conduct the simulations. Just tell `sCCIgen` your parameter file, and it will provide you the data and document you need! 




